name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'new-relic-deployment-marker/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'new-relic-deployment-marker/**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          cd new-relic-deployment-marker
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r test/requirements.txt

      - name: Run tests
        run: |
          python -m pytest -p no:cacheprovider test/test_unit.py --verbose --capture=no

  build-and-push-docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sykescottages/bitbucket-pipes:new-relic-deployment-marker
